version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup
          command: |            
            sudo pip install --ignore-installed setuptools
            sudo pip install urllib3 pyOpenSSL ndg-httpsclient pyasn1
            sudo cp -r ~/.ssh/* /root/.ssh
            mkdir -p ~/.zinuit
            mkdir -p /tmp/.zinuit
            cp -r ~/repo/* ~/.zinuit
            cp -r ~/repo/* /tmp/.zinuit

      - run:
          name: Install Zinuit (Production)
          command: sudo python ~/repo/playbooks/install.py --user travis --run-travis --production

      - run:
          name: Setup Tests
          command: |
            cd ~
            sudo pip install --upgrade pip
            sudo pip install -e ~/.zinuit

      - run:
          name: Run Tests
          command: sudo -E python -m unittest -v zinuit.tests.test_setup_production
