---
- name: Install deps
  yum: name="{{item}}" state=present
  with_items:
    - policycoreutils-python
    - selinux-policy-devel
  when: ansible_distribution == 'CentOS'

- name: Check enabled SELinux modules
  shell: semanage module -l
  register: enabled_modules
  when: ansible_distribution == 'CentOS'

- name: Copy metel_selinux policy
  copy: src=metel_selinux.te dest=/root/metel_selinux.te
  register: dest_metel_selinux_te
  when: ansible_distribution == 'CentOS'

- name: Compile metel_selinux policy
  shell: "make -f /usr/share/selinux/devel/Makefile metel_selinux.pp && semodule -i metel_selinux.pp"
  args:
    chdir: /root/
  when: "ansible_distribution == 'CentOS' and enabled_modules.stdout.find('metel_selinux') == -1 or dest_metel_selinux_te.changed"
...